### ISSUE TITLE
Changing the order of questions

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#11]
I tried to change the order of questions, but while I can do it in the backend part, and save it, then it does not show it in the online survey....why? what  am I missing?!

**Comment by nebogeo** [comment]
Not sure, I can't get this to not happen - I just swapped the age and sex questions and it seems to work. Are you saving it after doing this?

**Comment by alecini** [comment]
Ok I'll try again

**Comment by alecini** [comment]
Just tried to do that, still now working, what am I doing wrongly?!

it's in the questions:
Do these insects look familiar?
Click on all the ones you think you have seen near your home or work

then I put 
These are the insects you selected as "seen/familiar". Do you have a name for them? If so, please write, please write it down, otherwise, skip to the next question

then
Which of these insects are wasps?

but in the survey I still get "which are wasps" after the first question, in the place of "these are those you selected as familiars..."

**Comment by nebogeo** [comment]
Ahah - there are two orderings - categories and questions, you want to change the order of the categories as these questions are in different ones.

The order number in the questions sets their position in the category - I just kept them going up in number to make the admin list easier to read.

**Comment by alecini** [comment]
Great understood!
thanks
