### ISSUE TITLE
[necessary]: option none

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#15]
For some questions, we have to clunde the possibility of no answer.
for example, when we ask to recognize the insects, they might not recognize any of them. If the question is a required one (and it will be) we should add the possibility to say none of them. 

the same for the question: which of these are wasps/bees...we should include: none, like a button saying non of these.

**Comment by nebogeo** [comment]
I've added "None of the above" (these messages will need translating at some point actually)
