### ISSUE TITLE
[necessary]: I cannot understand how to select subset of insects

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#16]
I missed how to create subset of insects according to the answers/choices of the user.

say:
1) which insects are familiar...they choose x,y,z. 
We want them ask the names of these x,y,z insects, not all.
it seems to me this is already in place, but I cannot understand how to use it! sorry!

**Comment by nebogeo** [comment]
It is hard coded - the list of known insects is maintained, and used for the naming and the "insects feel" question.

**Comment by nebogeo** [comment]
Closing this one as you don't need to do anything :)
