### ISSUE TITLE
[necessary]: insert an information page between two questions

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#17]
at some point in the survey we need to insert a simple text + figures page in which they do not need to answer anything, only to read.
this is meant to give them feedback on what they did.

I think we will need some of these pages. I'll prepare text and figures, only need to know how to add such a kind of page

1) For example, after they indicated which insects they believe are wasps and which bees, we provide a page with the same photos, onto each one is written: this is a wasp, this is a bee.
I'll prepare text and photos, I just need to know how to add a simple page.
The user will then click on "follow the survey" button to go on with it.

2) After they saw the pollination/predation video and being asked about that, we need a page in which we explain the video.

3) after the entire survey, we need a finale page in which we thank them and tell them that they can get more info on wasps etc on our website.

**Comment by nebogeo** [comment]
Done - see new "Information" question type
