### ISSUE TITLE
[nice to have, not necessary]: direct visualization of part of the survey

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#18]
Currently, to visualize the survey we can only do it by looking at the entire survey.
It would help to be able to see directly the outcome of a single questions, something like "visualize the survey from here" in addition to visualize from the start...

**Comment by nebogeo** [comment]
To some extent you can dive into the middle of a survey using the URL e.g http://waspsurvey.fo.am/survey/1-7/

I use that when testing things - but it doesn't always do what you want as you need to go from the start to get the known insects list etc etc.

You might have noticed it remembers your answers to most questions - this is just a side effect of being logged in to the admin, it doesn't do that for normal access
