### ISSUE TITLE
[necessary]: different sets of questions according to users answers

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#19]
This is a point we partially discussed in issue# 9. I report it here in amore complete way. 

The survey targets different sets of people: basically two: farmers and people working in a farm, and NOT farmers (people not working or living close to a farm). We are interested in the opinion of both parts, but clearly the questions should be framed in a slightly different way.

So, we will have basically two pathways in the survey. the common part, and the part specific to either group FARMES or group NONFARMERS.
the difference in the questions is really small, but necessary (it's the last part of the survey, categories "this could be useful... for both bees/wasps" and "how can we help you to know more about bees/wasps".

Also, we need to be able to present a question only if the user has given some particular answer in the previous question. So, for example, in the section
ABOUT YOU:
the question on sex: if other , please specify. this should be present only if the person has selected other, otherwise it should not be visible.

**Comment by nebogeo** [comment]
The farmers/non-farmers selection is now working, with some caveats. I've added it to the current test survey already, but the steps are:

1. Click on the "Use for" menu for the "are you a farmer" question and select "User farmer question"
2. For any questions you want to hide from non-farmers, use the same menu and select "Hide if not farmer"
3. For the reverse, to hide a question from farmers select "Hide if farmer"

On the test survey the two farmer video questions now have two non-farmer worded video questions to match, and the "would you like to know more about wasps" category contains a new non-farmer question to demonstrate how it could work. 

Note that this doesn't work on the category level - you can't hide categories, but as long as there are equivalent questions to ask it works well.

**Comment by nebogeo** [comment]
Something interesting about the gender question: https://www.ruth-ng.co.uk/how-to-ask-about-gender-in-forms-respectfully/

I am quite interested why you need to ask this for the purposes of this study :)

**Comment by nebogeo** [comment]
Just did the magic other boxes and added them to the test survey, more in incoming email...
