### ISSUE TITLE
[nice to have, not necessary]: question with feedback to users

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#20]
We would like to give a real-time feedback to users about a few questions they provide answers for.
For example, question: which of these insects are wasps?
They can select several insects.
The we ask which are bees, they select again.

after these two questions, we provide them images with the tag on each insect: wasps, bees, to teach them which insects is which.
It would be nice if we could give the user also a score based on how many wasps have been correctly identified and how many bees, maybe also which one.

**Comment by nebogeo** [comment]
I would love to do this - in fact as part of a separate game type of thing with a full design it would be great, but it is indeed a little out of scope so lets see how we go with the necessary bits first

**Comment by alecini** [comment]
That would b e really nice, but yes, let's wait!
