### ISSUE TITLE
[highly recommended]: possibility to select an image as a wasp image  or a bee image

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#21]
instead of asking them "which of these is a wasp" and then "which of these is a bee" (which means showing them twice the same set of photos (i.e. 12 each time) it would be very nice to be able to put a single panel of insect photos, and ask them which are WASPS and which are BEES? 
and they could identify each one by clicking on one of three buttons, to be placed below each photo: wasp, bee, I do not know.

This would make the survey shorter and easier to be done...definitely better than asking them the same stuff many times!

**Comment by nebogeo** [comment]
Are there going to be insects that are neither wasps or bees?

**Comment by alecini** [comment]
Nope, just bees and wasps, and wasp with their nest and bees with their nest, but no other kind of animals

**Comment by nebogeo** [comment]
I guess it seems to me that the benefit of being able to tag a third state of "I don't know" on an insect doesn't seem worth the friction of having a more complex interface (which in general means less people will do it), but we can do this if you think it's worth it.

**Comment by alecini** [comment]
I see. However, my concern is that if a user can only select bee or wasp, it will be somehow forced to select one of the two. So, even by simple chance, some will correctly identify some species, thus biasing the result.
I think that users can also avoid clicking... but this is not so clear in the survey right now (and also, I'd like to make them FORCED to make a choice for each insect, so that there 's no risk of them skipping by mistake an image!).
I thus guess that by allowing them to explicitly say "i do not know" we will gather this important information...
then, we may want to discuss this point later, while resolving the other crucial points. We might find another way to do it without requiring too much changes maybe.

**Comment by nebogeo** [comment]
Yes I think this debate is a more philosophical nature than a technical one :) but from experience the more enforcement there is (mandatory fields etc) the less data you will get, as the more it feels like working for free, or filling out an irritating tax form. This can have a massive impact, so it needs to be thought through carefully.
