### ISSUE TITLE
Information category: how to insert long text and photos

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#26]
in the information bit category, i.e. where we are not asking but just providing info or feedback to the users, we need to be able to put text and/or photos, as we said. However I am currently unable to see how...
is there a way to put a text box (not for the users, but for us to provide info) below the title?
we would need that for example at the begging of the survey, when explaining the scope and the privacy issues.

Also, we would need to provide (after the who's a wasp and who's a bee questions) feedbacks about wasp and bee identity. That would be a panel  with the same photos and a tag on them: wasp, bee.

How to do that?

**Comment by nebogeo** [comment]
For the first part see #35 - the second part we previously agreed (#20) was a nice to have feature and out of scope of the original brief
