### ISSUE TITLE
Add a "duplicate survey" action to admin

### ISSUE THREAD

**Issue by nebogeo** [fo-am/waspsurvey#3]
Mainly I think useful for translations

**Comment by alecini** [comment]
Absolutely useful, not only for translations but also for creating slightly different versions and test which is better one.
Also, it would be very useful to be able to duplicate questions or set of questions WITHIN a survey, and also EXPORT/TRANSFER question or set of questions or items to other surveys...can it be implemented without too much effort?

**Comment by nebogeo** [comment]
I don't want to add too much behind the scenes functionality, because the emphasis should be on making it easier for participants but I think mostly this is repetition now in the wasp questions? This is currently designed so you can add any arbitrary questions there, so there is repetition. If you are likely to (as discussed) reduce this to only one "what are your feelings towards this insect" question then we can remove all that and collapse it into a single question that loops over each "known" insect (or each insect in the participants locality).

**Comment by alecini** [comment]
Hi Dave, 
thanks for your explanations.
my point was to:
a) be able to duplicate questions within the survey, without having to re-write them...it would be useful and would faste the creation of similar set of questions.
b) be able to copy an entire part of the survey into a second survey. We're gonna end up with just one survey, but we might need to create several different versions of the survey at some time, to test them. Having a simple "copu-paste" for the entire survey would be nice. Usually this takes the form of "duplicate and rename", or something like that.. did I manage to explain myself?!

are these already in or doable from your side?

**Comment by nebogeo** [comment]
I'd probably say that the copy individual questions is a "nice to have", but the duplicate + edit entire survey is more essential at this point...
