### ISSUE TITLE
[not crucial, but nice]: suggestions text within answer textbox

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#30]
in the questions where they are supposed to answer by inserting a text, is there a way to write something within the box, maybe in light grey, as a suggestion?
for example: type here your answer. (then when they type the text will disappear)

clearly, just if that's easy.

**Comment by nebogeo** [comment]
I looked into doing this, and it's problematic due to translations ("not recommended") so I left it out - we'll revisit when I look into the translations of fixed text: #24

**Comment by alecini** [comment]
Sure, no worries, really a minor thing, just if this was supereasy!
