### ISSUE TITLE
Style and colours

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#34]
I think we have to discuss and agree on the style of the survey. I guess the current style is the preliminary version. WHat are you thinking at for the final survey?
Seirian suggested this two as inspirations!
one for beekeepers: https://readingagriculture.eu.qualtrics.com/jfe/form/SV_50jkuWLstnmv8od
 one for growers: https://readingagriculture.eu.qualtrics.com/jfe/form/SV_0jjKgub4NVT4mB7

the style is super simple, but also professional.
I think we'd like to have something clean like this.
What do you think about?

**Comment by amberfoam** [comment]
The font was agreed very early on with Seirian (Noto) as it is one of the only ones that can be used in most languages, which means you won't get into formatting problems when you want to translate it later. The colours can be changed - just send over the colours you want! That's basically all there is for styling on this - font and colours.

**Comment by alecini** [comment]
Ok, I see.
What about the font size, bold, etc? (probably you're going to answer this in the other issue, but I put it here as well).

**Comment by nebogeo** [comment]
I've made it a bit less desaturated and reduced the font size - will appear on next update.
