### ISSUE TITLE
format

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#35]
Apparently I am not able to perform any style formatting on the text of the survey: size , font, colour, italic/bold...
also, in some case I need to divide the text into paragraphs..
how can I do that?

**Comment by nebogeo** [comment]
The text boxes allow you to add html formatting - so italic is `<i>italic text</i>` bold is `<b>bold text</b>` and paragraphs are `<p>this text is in a paragraph</p>`. I wouldn't recommend changing text sizes or colours if you want it to look clean stylistically, but that is possible in extreme cases...
