### ISSUE TITLE
Translation settings

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#37]
We are not sure yet how to handle the future translated version of the survey.
We'll do the translation but how to implement them on the survey?
We think the best option is to put a menu in the first page, where users can choose among one of the available options( we are thinking at english, spanish, portuguese, italian, french, so far, but clearly would need the possibility to expand this later).

**Comment by nebogeo** [comment]
The idea is that you can duplicate the survey when it's done, and then replace the text with the translations - each survey will then appear on the front page for people to choose between. There are also bits of additional text we'll need to translate see #24

**Comment by nebogeo** [comment]
You can set the "Users can see it and answer it" tick box on the survey to control which ones are visible on the front page.
