### ISSUE TITLE
how to add logo

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#38]
We will need to add logos of UCL and other collaborators, is it possible to create a background which remains there for the whole survey and where we can upload pictures of logos?

**Comment by nebogeo** [comment]
Yes - but it'll make more sense to hardcode it into the site, so please send (or attach here) the logos you need...

**Comment by alecini** [comment]
OK, but what if we need tom change the logos at some point? (i.e. an external partners asking for that, for example...) would it be possible?

**Comment by nebogeo** [comment]
Yeah sure - I'm also going to try adding a new image upload for general purpose images in question fields which might work for the logos too, but generally position them in a header/footer or something will be something I need to do.

**Comment by alecini** [comment]
great
