### ISSUE TITLE
adding pdf/big infographic

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#39]
IN the finale pages we will need to put a thank you page + an explanation page, where we give them feedback and explanation about the survey goal and the importance of wasps.
We  already have the way to pu "information bit page" but , in addition to text, we need to put pictures and/or pdfs (this will allow us to be independent about formatting of this part).

**Comment by nebogeo** [comment]
You can do this via html links and formatting (I'll add a demo on the test survey) see #35
