### ISSUE TITLE
insect photos selection

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#40]
I'm not sure I understood the logic behind insect photos selection.
We need to have the possibility to choose, for different questions, different subset of photos of insects. THis is probably feasible but, sorry, I cannot understand how to do that.
 in some questions we need to link this to previous questions (such as "name the insect") in other we will simply present them all.

**Comment by nebogeo** [comment]
There are already subsets in use for the different questions either based on locality or the "seen" selection that the user has selected - these are used in the relevant questions automatically... is there a specific problem that needs fixing here?

**Comment by nebogeo** [comment]
Happening at #41
