### ISSUE TITLE
open the final link in a new tab, to avoid lack of submissions

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#52]
as it stands, if one clicks on the link at the end of the survey, it is directed to the website, but in the same tab. this is ont that good, I'd prefer to have it in a new tab.
Apart from my taste, this creates the problem that poeple might think the survey is ended and answers submitted, while this happens only if the user click on button "next section".
It would be nice to replace "next section" here with SUBMIT THE ANSWERS, and to make it more evident that people have to click!

the top option would be to have the link in the very final page, i.e. after the submission when the website says: 
Survey submitted
Thanks! Your answers have been saved

and then add "You can find more info about wasps, bees, and the project at this website."

**Comment by nebogeo** [comment]
Would it work to display the website link on the "Thanks! Your answers have been saved" page?

**Comment by alecini** [comment]
Yes, that would be the solution

**Comment by nebogeo** [comment]
Then we can get rid of that last info box entirely

**Comment by nebogeo** [comment]
You won't be able to edit it, as I'll have to hardcode it - but if you are happy with it how it is, can copy it now

**Comment by alecini** [comment]
Sorry, I do not understand!
The solution I like is to have the website shown on the last page, where it says Thanks! Your answers have been saved".
I guess you mean that, if we will have to change the link, we won't be able to do that, is it so?
Well, I do not think it will happen often, only if we change the link...in such a case I guess we could ask your quick help?
