### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#8]
I was modifying the survey and I now get this error:

Request Method: | GET
-- | --
http://waspsurvey.fo.am/survey/1/
3.1.2
MultipleObjectsReturned
get() returned more than one Question -- it returned 2!
/home/dave/code/waspsurvey/.venv/lib/python3.7/site-packages/django/db/models/query.py, line 436, in get
/home/dave/code/waspsurvey/.venv/bin/python
3.7.3
['/home/dave/code/waspsurvey',  '/home/dave/code/waspsurvey',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/home/dave/code/waspsurvey/.venv/lib/python3.7/site-packages',  '/var/www/waspsurvey/']
Tue, 13 Oct 2020 16:40:29 +0000

**Comment by nebogeo** [comment]
Interesting, this seems happy at the moment. Do you remember more precisely what you were changing? Please try and break it again, it would be good to track down!!

**Comment by nebogeo** [comment]
Guessing this hasn't reoccured
