### ISSUE TITLE
LOGIC behind questions

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#9]
We need to be able to present a question only if the user has given some particular answer in the previous question. So, for example, in the section
ABOUT YOU:
the question on sex: if other , please specify. this should be present only if the person has selected other, otherwise it should not be visible.

same applies to: are you living/working in a farm...if they say yes we can ask them about the crop, otherwise, it should not be visible.

**Comment by nebogeo** [comment]
This is a trade off against making it the admin interface simple to use and not adding lots of parameters there. That's not to say we can't do it, but you may need to decide the priority of this against the other things you want as this is already growing beyond what we quoted for.

**Comment by alecini** [comment]
Hi, I am surprised that this go beyond the quote.. did not know..I'll talk about that with Seirian so that I can better understand what is within and what beyond.
Anyway, this specific point was already in the powerpoint we discussed together.
Indeed, we the powerpoint reports this and several other points in which we will need to create different subsets of questions according to what the users will say.
For example, we will have two different sets of questions if users are FARM or NON-FARM people.
Nothing complicated, just: If question A received answers a then apply set of questions X, if not, set of questions Y (some of the questions in both subsets will be the same, other will not).
Do you think it would be useful to go through the powerpoint again together so that maybe it's easier to talk about issues, feasibility etc? happy to do this when you prefer! thanks

**Comment by nebogeo** [comment]
It doesn't necessarily go beyond the quote, but a lot of other things are - so I'm pushing you a bit to see which features are really important - if some minor things that will take time can be dropped in favour of new things which might be more important.

**Comment by nebogeo** [comment]
I just checked and in the original ppt we based the quote on: "survey leaned.pptx" sent on 12 June, there were only 4 simple demographic questions. We expected a few more, but it's just an example of needing to prioritise what is essential first and what are "nice to haves" can wait until we know if we have enough time.

**Comment by alecini** [comment]
Really?
Oh gosh, that is not indeed the survey, demo infos is just the first "tiny adnb easy" part!
Quite weird indeed the powerpoint included only those points, as the quote included the other parts if I remember well,
Anyway, no worries. We'll find the way!
I think the admin you set up is very good and will allows us to build most of the survey, but there are three to four main things we might want to discuss together. do you prefer over github or through zoom? I can send you the final version of what we would like to have in the survey in a ppt...just tell me which way do you prefer.
